pushHour: 20
showTableName: true
autoRecallCode: false
renderScale: 1.0
autoCancelCheckEnabled: false    
autoCancelCheckInterval: 60
birthdayPushHour: 0
allowSelfModify: true
birthdayWhitelistGroups: []
birthdayBlacklistGroups: []
# 中转服务地址（例如 http://YOUR_SERVER_URL:19178）
# 留空或删除则使用直连官方API(现已不可用)
proxyUrl: ""
# 中转服务鉴权 Token, 如有需要请联系插件作者获取
apiToken: ""
# 默认学期开始日期
defaultSemesterStart: "2026-03-02"
# 自定义bot名称
botName: ""
# 字体风格
font: "像素"
# 群课表排序方式 userId：按QQ号；courseStatus：按上课状态
sortMode: "userId"