pushHour: 20
showTableName: true
autoRecallCode: false
renderScale: 1.0
autoCancelCheckEnabled: false    
autoCancelCheckInterval: 60
birthdayPushHour: 0
allowSelfModify: true
birthdayWhitelistGroups: []
birthdayBlacklistGroups: []